# -*- coding: utf-8 -*-
"""url_viz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TTO8Eho9ziuNWiXHquDs6dHj1ijLTC9
"""

from pathlib import Path
import requests
import networkx as nx
import nxviz as nv
import matplotlib as mpl
import matplotlib.pyplot as plt
from datetime import datetime, date
from pprint import pprint as pp
from itertools import combinations
import random
from collections import Counter, defaultdict

import pandas as pd

df = pd.read_csv("/content/all_url.csv")

df.head()

df = df[df.month != 2019]

url_graph = nx.from_pandas_edgelist(df,source= 'month', target ="section")

nx.info(url_graph)

url_graph.nodes()

nx.draw(url_graph, with_labels=True)

sub_graph = nx.from_pandas_edgelist(df,source= 'section', target ="subsection")

fig = plt.figure(1, figsize=(60, 30), dpi=30)
nx.draw(sub_graph, with_labels=True, font_size = 40, node_size = 4000, width = 3)
#labels=nx.draw_networkx_labels(sub_graph,font_size=30)

data = nx.DiGraph()
t_131.add_nodes_from(attr)
t_131.add_edges_from(data)
nx.set_node_attributes(t_131, attr)